---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kubelet-csr-approver/flux-sync.yaml
  - ./local-path-provisioner/flux-sync.yaml
  - ./metrics-server/flux-sync.yaml
