---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-nas
  namespace: flux-system
spec:
  gitImplementation: go-git
  ignore: |
    # exclude all
    /*
    # include kubernetes directory only
    !/kubernetes
  interval: 10m
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/tyriis/talos-nas.git
