---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-metallb
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 30m
  retryInterval: 15s
  timeout: 3m
  path: ./kubernetes/apps/metallb-system/metallb/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kube-nas
  dependsOn:
    - name: apps-cert-manager
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-metallb-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 30m
  retryInterval: 15s
  timeout: 3m
  path: ./kubernetes/apps/metallb-system/metallb/config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kube-nas
  dependsOn:
    - name: apps-metallb
      namespace: flux-system
