---
clusterName: kube-nas
talosVersion: v1.3.6
kubernetesVersion: v1.26.1
endpoint: https://192.168.1.57:6443
allowSchedulingOnMasters: true
cniConfig:
  name: flannel
nodes:
  - hostname: kube-nas
    ipAddress: 192.168.1.57
    installDisk: /dev/nvme0n1
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true

controlPlane:
  inlinePatch:
    machine:
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          op: create
          path: /var/cri/conf.d/allow-unpriv-ports.toml
      sysctls:
        fs.inotify.max_user_instances: "8192"
        fs.inotify.max_user_watches: "1048576"
      time:
        disabled: false
        servers:
          - 192.168.1.1
          - time.cloudflare.com
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
          rotate-server-certificates: "true"
    # - "@./extraKernelArgs-patch.yaml"
    - |-
      - op: add
        path: /cluster/extraManifests
        value:
          - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml

  # configPatches:
  #   # deploy metrics server
  #   # https://www.talos.dev/v1.0/kubernetes-guides/configuration/deploy-metrics-server/
  #   # !!! when doing this it is broken when installing it with flux helmrelease !!!
  #   - op: add
  #     path: /cluster/extraManifests
  #     value:
  #       - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
  #     - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  # - op: add
  #   path: /machine/install/extraKernelArgs
  #   value:
  #     - talos.logging.kernel=udp://10.45.0.2:6050/
  # - op: add
  #   path: /cluster/apiServer/extraArgs
  #   value:
  #     feature-gates: MixedProtocolLBService=true,GracefulNodeShutdown=true,EphemeralContainers=true
  # - op: add
  #   path: /cluster/controllerManager/extraArgs
  #   value:
  #     feature-gates: MixedProtocolLBService=true,GracefulNodeShutdown=true,EphemeralContainers=true
  # - op: add
  #   path: /cluster/proxy/extraArgs
  #   value:
  #     feature-gates: MixedProtocolLBService=true,GracefulNodeShutdown=true,EphemeralContainers=true
  # - op: add
  #   path: /cluster/scheduler/extraArgs
  #   value:
  #     feature-gates: MixedProtocolLBService=true,GracefulNodeShutdown=true,EphemeralContainers=true
  # - op: add
  #   path: /machine/kubelet/extraArgs
  #   value:
  #     feature-gates: MixedProtocolLBService=true,GracefulNodeShutdown=true,EphemeralContainers=true
  #     rotate-server-certificates: true

# worker:
#   inlinePatch:
#     machine:
#       files:
#         - content: |
#             [plugins."io.containerd.grpc.v1.cri"]
#               enable_unprivileged_ports = true
#               enable_unprivileged_icmp = true
#           op: create
#           path: /var/cri/conf.d/allow-unpriv-ports.toml
#       sysctls:
#         fs.inotify.max_user_instances: "8192"
#         fs.inotify.max_user_watches: "1048576"
#       time:
#         disabled: false
#         servers:
#           - 192.168.1.1
#           - time.cloudflare.com
#   configPatches:
#     - op: add
#       path: /machine/kubelet/extraArgs
#       value:
#         feature-gates: MixedProtocolLBService=true,GracefulNodeShutdown=true,EphemeralContainers=true
#         rotate-server-certificates: true
