---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-sync
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: kube-nas
  decryption:
    provider: sops
    secretRef:
      name: age-key
  # postBuild:
  #   substituteFrom:
  #     - kind: ConfigMap
  #       name: cluster-settings
  #       optional: false
  #     - kind: Secret
  #       name: cluster-secrets
  #       optional: false
