---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-server
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: Recreate
    image:
      repository: ghcr.io/tyriis/docker-nfs-server
      tag: v0.1.3
    securityContext:
      # privileged: true
      capabilities:
        add:
        - SYS_ADMIN
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SETTING_METALLB_NFS_ADDR}"
        ports:
          http:
            enabled: false
          nfs:
            port: 2049
            protocol: TCP
    persistence:
      nfs:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/usb1/nfs
        hostPathType: DirectoryOrCreate
        mountPath: /nfs
    env:
      NFS_EXPORT_0: /nfs 192.168.1.0/32(rw,no_subtree_check)
