---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nas-system
resources:
  - ./helm-release.yaml
commonLabels:
  app.kubernetes.io/name: nfs-server
  app.kubernetes.io/instance: nfs-server
