---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
data:
  SETTING_CLUSTERNAME: kube-nas
  SETTING_TZ: Europe/Vienna
  SETTING_GATEWAY: 192.168.1.1
  SETTING_METALLB_LB_RANGE: 192.168.1.90-192.168.1.99
  SETTING_METALLB_TRAEFIK_ADDR: 192.168.1.90
