# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    labels:
        kustomize.toolkit.fluxcd.io/prune: disabled
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ru8/OQ9OEklpcIOh,iv:lRHo0Cvom7daSv6dcwR0xMbbBes0tRFDCYI1SGSUgg8=,tag:tC65IBVx5h5PYbAnyHzFDg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:C5lridBfdln/yyPV3s44V0z9cXE=,iv:xR2OO4liVWdStZv7pMx5nIcIv4lwEcUY8cSRJDQJsz8=,tag:fKmLUDr1syu58gDC9tN8aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T23:48:49Z"
    mac: ENC[AES256_GCM,data:iPWI+zTCVzfKzS+lWa61PJ0WInJcAieD3qsA4vM7aENxUMRaLE5X7TIqi+Sdv6cpxxHT97uw4gbSapnG3Rm8PhJZJbPhsFlulIl0OlXiH9PxNEJbz5okWFC3DpBnszloXkrz0o76UznDOSSwBSDcZ1kdRGH2g34VaUsQjsPw/BY=,iv:LaxHhoa54ai7CRt5g3SsEQoOduRg1tiWsewvncEtNFw=,tag:5ogZV/vHz7JcMUhn3mSzOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
