---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-weave-gitops
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/flux-system/weave-gitops/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-nas
  wait: true
  timeout: 3m
