---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-nas
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/cert-manager/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-nas
  wait: true
  dependsOn:
    - name: apps-cert-manager
  timeout: 3m
